# geektimeC makefile


all: GEEKTIMEC
	@echo
	@echo ===== All GEEKTIMEC modules are Made =====
	@echo

clean: CLGEEKTIMEC
	@echo
	@echo ===== All GEEKTIMEC modules are Cleaned =====
	@echo


GEEKTIMEC: make01  

CLGEEKTIMEC: clean01  


# make

make01:
	@cd 01 && make



# clean

clean01:
	@cd 01 && make clean

